# Generated by Django 2.2.5 on 2023-05-22 15:08

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contacte ta salle de sport', max_length=31)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('map', models.CharField(max_length=555)),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='code',
            name='token',
            field=models.CharField(default='779f89e3-e8f9-4b40-8d89-91169933988e', max_length=80, unique=True),
        ),
    ]
