# Generated by Django 2.2.5 on 2023-05-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_auto_20230522_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='salle',
            field=models.ManyToManyField(blank=True, to='coach.salle'),
        ),
        migrations.AddField(
            model_name='salle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='token',
            field=models.CharField(default='662ef4e2-06eb-4856-8128-64866a75b0d5', max_length=80, unique=True),
        ),
    ]
