# Generated by Django 2.2.5 on 2023-05-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_auto_20230523_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='token',
            field=models.CharField(default='8d7f9c1a-4559-4537-b0a3-874aa4745450', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='clients', to='client.client'),
        ),
    ]
