# Generated by Django 2.2.5 on 2023-05-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_auto_20230524_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='token',
            field=models.CharField(default='283fd45d-a73e-4c67-9d0a-d38968226ce9', max_length=80, unique=True),
        ),
    ]
