# Generated by Django 2.2.5 on 2023-05-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_auto_20230524_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='token',
            field=models.CharField(default='fa20198e-6b67-4164-b48f-f9c7819ca82c', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='client.client'),
        ),
    ]
