# Generated by Django 2.2.5 on 2023-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_auto_20230524_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='comment',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='code',
            name='token',
            field=models.CharField(default='88fe47ab-5a83-4d06-a60d-9b396c4e511e', max_length=80, unique=True),
        ),
    ]
